trigger:
  batch: true
  branches:
    include:
      - master

pr: none

pool:
  vmImage: 'windows-2022'

variables:
  BuildConfiguration: 'Release'
  Major: '7'
  Minor: '8'

name: $(date:yyyy)$(DayOfYear)$(rev:rrr)
steps:

  - task: DownloadSecureFile@1
    name: keystore
    inputs:
      secureFile: 'Money Fox.keystore'

  - task: JavaToolInstaller@0
    displayName: 'Install Java 11'
    inputs:
      versionSpec: '11'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'

  - task: PowerShell@2
    displayName: 'Install maui workload'
    inputs:
      targetType: 'inline'
      script: 'dotnet workload install maui --ignore-failed-sources'

  - task: android-manifest-version@1
    inputs:
      sourcePath: 'Src/MoneyFox.Android/Properties/AndroidManifest.xml'
      versionCodeOption: 'buildid'
      versionCode: '$(Build.BuildNumber)'
      versionCodeOffset: '0'
      versionName: '$(Major).$(Minor).$(Build.BuildId)'
      printFile: true

  - task: DotNetCoreCLI@2
    displayName: 'Run Tests'
    inputs:
      command: 'test'
      projects: '**/*.Tests.csproj'
      arguments: '--configuration $(BuildConfiguration)'

  - task: DotNetCoreCLI@2
    displayName: 'build Android app'
    inputs:
      command: 'publish'
      publishWebProjects: false
      projects: '**/MoneyFox.Android.csproj'
      arguments: '-c Release -f net6.0-android /p:AndroidKeyStore=True /p:AndroidSigningKeyAlias=$(KeyStoreAlias) /p:AndroidSigningKeyStore=$(keystore.secureFilePath) /p:AndroidSigningKeyPass=$(KeyStorePass) /p:AndroidSigningStorePass=$(KeyStorePass)'

  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
    inputs:
      SourceFolder: '
      Contents: '**/*.aab'
      TargetFolder: '$(build.artifactstagingdirectory)'
      flattenFolders: true

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'
