trigger:
  batch: true
  branches:
    include:
      - master

pr: none

pool:
  vmImage: 'macOS-12'

variables:
  Major: '7'
  Minor: '8'

steps:
  - task: UseDotNet@2
    displayName: 'Use correct .Net sdk'
    inputs:
      version: 6.x

  - task: PowerShell@2
    displayName: "Set App Version"
    inputs:
      targetType: 'inline'
      script: |
        $Version = Get-Date -Format 'yyyyMMds'
        $DisplayVersion = "$(Major).$(Minor).$(Build.BuildId)'"

        Write-Host "DisplayVersion:" $DisplayVersion
        Write-Host "Version:" $Version

        [xml]$xml = Get-Content -Path ./src/MoneyFox.Ui/MoneyFox.Ui.csproj
        $xml.Project.PropertyGroup[0].ApplicationDisplayVersion = "$DisplayVersion"
        $xml.Project.PropertyGroup[0].ApplicationVersion = "$Version"
        Set-Content "./src/MoneyFox.Ui/MoneyFox.Ui.csproj" -Value $xml.InnerXml -Force
        Write-Host $xml.InnerXml
      pwsh: true
    env:
      Major: $(Major)
      Minor: $(Minor)

  - task: InstallAppleCertificate@2
    displayName: 'Install an Apple certificate'
    inputs:
      certSecureFile: 'MoneyFox_Distribution_2022.p12'
      certPwd: '$(P12password)'
      keychain: temp

  - task: InstallAppleProvisioningProfile@1
    displayName: 'Install an Apple provisioning profile'
    inputs:
      provProfileSecureFile: 'MoneyFox_Distribution_2022.mobileprovision'

  - task: PowerShell@2
    displayName: "install maui workload"
    inputs:
      targetType: 'inline'
      script: 'dotnet workload install maui'

  - task: DotNetCoreCLI@2
    displayName: 'Run Tests'
    inputs:
      command: 'test'
      projects: |
        **/*.Tests.csproj

  - task: DotNetCoreCLI@2
    displayName: 'Build iOS app'
    inputs:
      command: 'publish'
      publishWebProjects: false
      zipAfterPublish: false
      projects: '**/MoneyFox.Ui.csproj'
      arguments: '-c Release -f net6.0-ios -o $(build.artifactstagingdirectory) /p:BuildIpa=true /p:Codesignkey="$(APPLE_CERTIFICATE_SIGNING_IDENTITY)" /p:CodesignProvision="$(APPLE_PROV_PROFILE_UUID)"'

  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        $sourceRoot = '$(system.defaultworkingdirectory)/assets/metadata'
        Copy-Item -Path $sourceRoot  -Destination $(build.artifactstagingdirectory) -Recurse

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'
