trigger:
  batch: true
  branches:
    include:
      - master

pr: none

pool:
  vmImage: 'windows-2022'

variables:
  BuildConfiguration: 'Release'
  Major: '7'
  Minor: '8'

name: $(date:yyyy)$(DayOfYear)$(rev:rrr)
steps:

  - task: android-manifest-version@1
    inputs:
      sourcePath: 'Src/MoneyFox.Ui/Platforms/Android/AndroidManifest.xml'
      versionCodeOption: 'buildid'
      versionCode: '$(Build.BuildNumber)'
      versionCodeOffset: '0'
      versionName: '$(Major).$(Minor).$(Build.BuildId)'
      printFile: true

  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        [xml]$xml = Get-Content -Path ./src/MoneyFox.Ui/MoneyFox.Ui.csproj
        $xml.Project.PropertyGroup[0].ApplicationVersion = "123"
        Set-Content "./src/MoneyFox.Ui/MoneyFox.Ui.csproj" -Value $xml.InnerXml -Force
      pwsh: true

  - task: DownloadSecureFile@1
    name: keystore
    inputs:
      secureFile: 'Money Fox.keystore'

  - task: JavaToolInstaller@0
    displayName: 'Install Java 11'
    inputs:
      versionSpec: '11'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'

  - task: PowerShell@2
    displayName: 'Install maui workload'
    inputs:
      targetType: 'inline'
      script: 'dotnet workload install maui --ignore-failed-sources'

  - task: DotNetCoreCLI@2
    displayName: 'build Android app'
    inputs:
      command: 'publish'
      publishWebProjects: false
      projects: '**/MoneyFox.Ui.csproj'
      arguments: '-c Release -f net6.0-android /p:AndroidKeyStore="True" /p:AndroidSigningKeyAlias="$(KeyStoreAlias)" /p:AndroidSigningKeyStore="$(keystore.secureFilePath)" /p:AndroidSigningKeyPass="$(KeyStorePass)" /p:AndroidSigningStorePass="$(KeyStorePass)"'

  - task: DotNetCoreCLI@2
    displayName: 'Run Tests'
    inputs:
      command: 'test'
      projects: '**/*.Tests.csproj'
      arguments: '--configuration $(BuildConfiguration)'
      
  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)'
      Contents: '**/*.aab'
      TargetFolder: '$(build.artifactstagingdirectory)'
      flattenFolders: true

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'
