pr:
  branches:
    include:
      - master

jobs:

  - job: BuildiOS
    displayName: "Run Tests MacOS and Build iOS"
    pool:
      vmImage: 'macOS-12'

    variables:
      solution: '**/MoneyFox.Mobile.sln'

    steps:
        
      #- script: sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh 6_12_0
      #  displayName: 'Select the Xamarin SDK version 6.12.0'

      #- script: echo '##vso[task.setvariable variable=MD_APPLE_SDK_ROOT;]'/Applications/Xcode_12.2.app;sudo xcode-select --switch /Applications/Xcode_12.2.app/Contents/Developer
      #  displayName: 'Updating xcode version'

      - task: InstallAppleCertificate@2
        displayName: 'Install an Apple certificate'
        inputs:
          certSecureFile: 'MoneyFox_Distribution_2022.p12'
          certPwd: '$(P12password)'
          keychain: 'temp'

      - task: InstallAppleProvisioningProfile@1
        displayName: 'Install an Apple provisioning profile'
        inputs:
          provisioningProfileLocation: 'secureFiles'
          provProfileSecureFile: 'MoneyFox_Distribution_2022.mobileprovision'

      - task: UseDotNet@2
        displayName: Install DotNet SDK
        inputs:
          packageType: 'sdk'
          version: '6.x'
          includePreviewVersions: false

      - task: DotNetCoreCLI@2
        displayName: "Install MAUI workload"
        inputs:
          command: 'custom'
          custom: 'workload '
          arguments: 'install maui --source https://api.nuget.org/v3/index.json'

      - task: DotNetCoreCLI@2
        displayName: "Build iOS Project"
        inputs:
          command: 'publish'
          projects: 'Src/MoneyFox.Android/MoneyFox.Android.csproj'
          arguments: '-c $(BuildConfiguration) -f net6.0-ios -o $(build.binariesdirectory)/$(BuildConfiguration)'

      - task: DotNetCoreCLI@2
        displayName: 'Run Tests'
        inputs:
          command: 'test'
          projects: |
            **/*.Tests.csproj
          arguments: '--configuration $(BuildConfiguration)'

      - task: XamariniOS@2
        displayName: 'Build Xamarin.iOS '
        enabled: false
        inputs:
          solutionFile: Src/MoneyFox.Ios/MoneyFox.iOS.csproj
          configuration: '$(BuildConfiguration)'
          signingIdentity: $(APPLE_CERTIFICATE_SIGNING_IDENTITY)
          signingProvisioningProfileID: $(APPLE_PROV_PROFILE_UUID)

  - job: BuildAndroid
    displayName: "Build Android"
    pool:
      vmImage: windows-2022

    variables:
      solution: '**/MoneyFox.Mobile.sln'

    steps:
      
      - task: DotNetCoreCLI@2
        displayName: "Install MAUI workload"
        inputs:
          command: 'custom'
          custom: 'workload '
          arguments: 'install maui --source https://api.nuget.org/v3/index.json'

      - task: JavaToolInstaller@0
        displayName: 'Install Java 11'
        enabled: false
        inputs:
          versionSpec: '11'
          jdkArchitectureOption: 'x64'
          jdkSourceOption: 'PreInstalled'
          
      - task: DotNetCoreCLI@2
        displayName: "Build Android Project"
        inputs:
          command: 'publish'
          projects: 'Src/MoneyFox.Android/MoneyFox.Android.csproj'
          arguments: '-c $(BuildConfiguration) -f net6.0-android -o $(build.binariesdirectory)/$(BuildConfiguration)'

      - task: DotNetCoreCLI@2
        displayName: 'Run Tests'
        inputs:
          command: 'test'
          projects: |
            **/*.Tests.csproj
          arguments: '--configuration $(BuildConfiguration) --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover'

      - task: XamarinAndroid@1
        displayName: 'Build Android Project'
        enabled: false
        inputs:
          projectFile: Src/MoneyFox.Android/MoneyFox.Android.csproj
          outputDirectory: '$(build.binariesdirectory)/$(BuildConfiguration)'
          configuration: '$(BuildConfiguration)'
          msbuildVersionOption: latest
          msbuildArchitectureOption: x64
          msbuildArguments: '/p:JavaSdkDirectory="$(JAVA_HOME)/"'

  - job: BuildAndTestWinUI
    displayName: "Build WinUI and Run Tests"
    pool:
      vmImage: windows-2022

    variables:
      solution: '**/*.wapproj'
      appxPackageDir: '$(build.artifactStagingDirectory)\AppxPackages\\'

    steps:
      - task: DownloadSecureFile@1
        displayName: 'Download Windows Certificate'
        name: 'signingCert'
        inputs:
          secureFile: 'MoneyFoxCert_2021.pfx'

      - powershell: |
          $pfxpath = '$(signingCert.secureFilePath)'
          $certPassword = $env:CERT_PASSWORD_ENV

          Add-Type -AssemblyName System.Security
          $cert = New-Object System.Security.Cryptography.X509Certificates.X509Certificate2
          $cert.Import($pfxpath, $certPassword, [System.Security.Cryptography.X509Certificates.X509KeyStorageFlags]"PersistKeySet")
          $store = new-object system.security.cryptography.X509Certificates.X509Store -argumentlist "MY", CurrentUser
          $store.Open([System.Security.Cryptography.X509Certificates.OpenFlags]"ReadWrite")
          $store.Add($cert)
          $store.Close()
        displayName: 'Install Cert'
        env:
          CERT_PASSWORD_ENV: $(UWP_Certificate_Password)

      - task: PowerShell@2
        displayName: "Set AppManifest"
        inputs:
          targetType: 'inline'
          script: |
            [xml]$xmlDoc = Get-Content '$(Build.SourcesDirectory)\src\MoneyFox.Win\MoneyFox.Win (Package)\Package.appxmanifest'
            $xmlDoc.Package.Identity.Name="57598ApplySolutionsSoftwa.MoneyFox"
            $xmlDoc.Package.Identity.Publisher="CN=071307B1-B0E3-434A-AD0E-FFF714A7245C"
            $xmlDoc.Save('$(Build.SourcesDirectory)\src\MoneyFox.Win\MoneyFox.Win (Package)\Package.appxmanifest')
          failOnStderr: true

      - task: PowerShell@2
        displayName: "Set Store Association"
        inputs:
          targetType: 'inline'
          script: |
            [xml]$xmlDoc = Get-Content '$(Build.SourcesDirectory)\src\MoneyFox.Win\MoneyFox.Win (Package)\Package.StoreAssociation.xml'
            $xmlDoc.StoreAssociation.Publisher="CN=071307B1-B0E3-434A-AD0E-FFF714A7245C"
            $xmlDoc.StoreAssociation.ProductReservedInfo.MainPackageIdentityName="57598ApplySolutionsSoftwa.MoneyFox"
            $xmlDoc.Save('$(Build.SourcesDirectory)\src\MoneyFox.Win\MoneyFox.Win (Package)\Package.StoreAssociation.xml')
          failOnStderr: true

      - task: UseDotNet@2
        displayName: Use .NET 6.0
        enabled: false
        inputs:
          packageType: 'sdk'
          version: '6.0.x'

      - task: NuGetToolInstaller@1
        displayName: 'Use NuGet'
        inputs:
          versionSpec: 6.x

      - task: DotNetCoreCLI@2
        displayName: Restore NuGets
        inputs:
          command: 'restore'
          projects: '**/*.csproj'
          feedsToUse: 'select'

      - task: DotNetCoreCLI@2
        displayName: 'Run Tests'
        inputs:
          command: 'test'
          projects: |
            **/*.Tests.csproj
          arguments: '--configuration $(BuildConfiguration) --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover'

      - task: VSBuild@1
        displayName: 'Build WinUI Project'
        inputs:
          solution: '$(solution)'
          msbuildArgs: '/p:AppxBundlePlatforms="x86|x64|arm64" /p:AppxPackageDir="$(appxPackageDir)" /p:AppxBundle=Always /p:UapAppxPackageBuildMode=CI'
          platform: x64
          configuration: '$(BuildConfiguration)'
