trigger:
  batch: true
  branches:
    include:
      - master

pr: none

pool:
  vmImage: 'macOS-12'

variables:
  Major: '7'
  Minor: '8'

steps:
  - task: UseDotNet@2
    displayName: 'Use correct .Net sdk'
    inputs:
      version: 6.x

  #- script: sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh 6_12_0
  #  displayName: 'Select the Xamarin SDK version 6.12.0'

  #- script: echo '##vso[task.setvariable variable=MD_APPLE_SDK_ROOT;]'/Applications/Xcode_12.1.app;sudo xcode-select --switch /Applications/Xcode_12.app/Contents/Developer
  #  displayName: 'Updating xcode version'

  - bash: |
      # Write your commands here

      echo "Build Script started.."

      echo 'Updating fastlane...'
      sudo gem install fastlane

      echo $Major
      echo $Minor
      echo $BUILD_BUILDNUMBER

      VERSION=$Major.$Minor.$BUILD_BUILDID
      echo $VERSION

      INFO_PLIST_FILE=$BUILD_REPOSITORY_LOCALPATH/Src/MoneyFox.Ios/Info.plist
      echo $INFO_PLIST_FILE

      echo "Updating version name to $VERSION_NAME in Info.plist"
      plutil -replace CFBundleShortVersionString -string $BUILD_BUILDNUMBER $INFO_PLIST_FILE
      plutil -replace CFBundleVersion -string $VERSION $INFO_PLIST_FILE
    displayName: 'Set App Version'
    env:
      Major: $(Major)
      Minor: $(Minor)

  - task: InstallAppleCertificate@2
    displayName: 'Install an Apple certificate'
    inputs:
      certSecureFile: 'MoneyFox_Distribution_2022.p12'
      certPwd: '$(P12password)'
      keychain: temp

  - task: InstallAppleProvisioningProfile@1
    displayName: 'Install an Apple provisioning profile'
    inputs:
      provProfileSecureFile: 'MoneyFox_Distribution_2022.mobileprovision'

  - task: PowerShell@2
    displayName: "install maui workload"
    inputs:
      targetType: 'inline'
      script: 'dotnet workload install maui --ignore-failed-sources'

  - task: DotNetCoreCLI@2
    displayName: 'Build iOS app'
    inputs:
      command: 'publish'
      publishWebProjects: false
      projects: '**/MoneyFox.iOS.csproj'
      arguments: '-c Release -f net6.0-ios /p:ArchiveOnBuild=True /p:Codesignkey="$(APPLE_CERTIFICATE_SIGNING_IDENTITY)" /p:CodesignProvision="$(APPLE_PROV_PROFILE_UUID)"'

  - task: DotNetCoreCLI@2
    displayName: 'Run Tests'
    inputs:
      command: 'test'
      projects: |
        **/*.Tests.csproj

  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
    inputs:
      SourceFolder: '$(system.defaultworkingdirectory)'
      Contents: '**/*.ipa'
      TargetFolder: '$(build.artifactstagingdirectory)'
      flattenFolders: true

  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        $sourceRoot = '$(system.defaultworkingdirectory)/assets/metadata'
        Copy-Item -Path $sourceRoot  -Destination $(build.artifactstagingdirectory) -Recurse

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'
