name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

env:
    DOTNETVERSION: 6.0.400
    ANDROID_PROJECT_PATH: "src/MoneyFox.Android/MoneyFox.Android.csproj"

jobs:
  buildAndroid:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '${{env.DOTNETVERSION}}'

    - name: Install MAUI Workload
      run: dotnet workload install maui --ignore-failed-sources

    - name: Restore Dependencies
      run: dotnet restore ${{env.ANDROID_PROJECT_PATH}}

    - name: Build MAUI Android
      run: dotnet publish ${{env.ANDROID_PROJECT_PATH}} -c Release -f net6.0-android --no-restore

    - name: Upload Android Artifact
      if: github.ref == 'refs/heads/master'
      uses: actions/upload-artifact@v3.1.0
      with:
        name: moneyfox-android-build
        path: src/MoneyFox.Android/bin/Release/net6.0-android/*Signed.a*
